### ISSUE TITLE
[FEAT] 앱 내 코드에서 예상치 못한 Exception 발생 시 처리

### ISSUE THREAD

**Issue by inourbubble2** [Team-Pravo/Pravo-Client#53]
## 🚀 작업 설명
앱 내 크래시 발생 시 처리하기

## 🌱 작업 상세 내용
- [ ] 에러 발생 시 앱이 멈추지 않고, 에러 모달 노출 이후 지속 실행 가능하도록 처리
- [ ] Sentry 연동?

**Comment by inourbubble2** [comment]
![image](https://github.com/user-attachments/assets/7d9e7e3e-26cc-4d04-9082-047de79da90e)
![image](https://github.com/user-attachments/assets/22ab6066-75ff-492a-93e9-b07b962997a9)

어떠한 화면 조회를 했는데 에러가 발생했다면 위와 같은 에러 페이지를 보여주는 게 맞을 것 같고,
어떤 인터랙션(버튼 클릭 등)을 했는데 에러가 발생했다면 모달을 띄어주는 게 맞을 것 같은데
에러 페이지에 어떤 요소가 들어가는 게 좋을까요..!?! @gaeguul

**Comment by gaeguul** [comment]
> 어떠한 화면 조회를 했는데 에러가 발생했다면 위와 같은 에러 페이지를 보여주는 게 맞을 것 같고, 어떤 인터랙션(버튼 클릭 등)을 했는데 에러가 발생했다면 모달을 띄어주는 게 맞을 것 같은데 에러 페이지에 어떤 요소가 들어가는 게 좋을까요..!?! @gaeguul

보증금 결제 실패 시에는 현재 아래와 같은 페이지로 리디렉션하려고 작업 중입니다! 네트워크 연결 에러 포함해서 전반적인 에러 다룰 수 있는 화면이 필요할까요?

![image](https://github.com/user-attachments/assets/7c74c417-e144-4b42-bac4-a8114cc48638)

**Comment by inourbubble2** [comment]
@gaeguul 헉 지금 화면도 너무 좋아요!! 저 공통 모듈로 빼서 메시지만 커스텀 가능하면 너무 좋을 것 같습니다 ~!! 단순 조회 실패에서도 저 화면 보여주면 좋을 것 같아요!
